# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0003_country_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='likes_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043b\u0430\u0439\u043a\u043e\u0432'),
        ),
    ]
