# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0004_city_likes_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': '\u0413\u043e\u0440\u043e\u0434', 'verbose_name_plural': '\u0413\u043e\u0440\u043e\u0434\u0430'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0430', 'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u044b'},
        ),
    ]
