# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0005_auto_20160421_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0430', 'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u044b'},
        ),
    ]
