# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0006_auto_20160423_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['date_joined'], 'verbose_name': '\u0427\u0435\u043b\u043e\u0432\u0435\u043a', 'verbose_name_plural': '\u041b\u044e\u0434\u0438'},
        ),
    ]
