# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0007_auto_20160428_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('person', 'content_type', 'object_id')]),
        ),
    ]
