# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0008_auto_20160505_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u0422\u0435\u0433', 'verbose_name_plural': '\u0422\u0435\u0433\u0438'},
        ),
    ]
