# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0009_auto_20160506_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_start',
            field=models.DateField(db_index=True, verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430'),
        ),
    ]
