# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0010_auto_20160512_0006'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tag',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
