# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0012_auto_20160512_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
        ),
    ]
