# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0013_auto_20160512_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='country',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(db_index=True, max_length=100, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
