# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0014_auto_20160531_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'profile_images/', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
